import type { Metadata } from "next";

import "./globals.css";

import Footer from "@/components/footer";
import LeftFixedHeader from "@/components/header/LeftFixedHeader";
import RightFixedHeader from "@/components/header/RightFixedHeader";
import Header from "@/components/header/Header";
import ClientOnly from "@/components/ClientOnly/ClientOnly";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientOnly>
          <LeftFixedHeader />
          <RightFixedHeader />
          <Header />
        </ClientOnly>
        {children}
        <ClientOnly>
          <Footer />
        </ClientOnly>
      </body>
    </html>
  );
}
